origins:
  - owner: resonatehq
    repo: examples-ts
    ref: main
  - owner: resonatehq
    repo: examples-py
    ref: main
  - files:
      pattern: ./docs/get-started/typescript-quickstart/code/part-1/src/**.ts
      owner: resonatehq
      repo: docs
      ref: main
  - files:
      pattern: ./docs/get-started/python-quickstart/code/part-1/src/**/**.py
      owner: resonatehq
      repo: docs
      ref: main
  - files:
      pattern: ./docs/get-started/typescript-quickstart/code/part-2/src/**.ts
      owner: resonatehq
      repo: docs
      ref: main
  - files:
      pattern: ./docs/get-started/python-quickstart/code/part-2/src/**/**.py
      owner: resonatehq
      repo: docs
      ref: main

targets:
  - docs/get-started/typescript-quickstart/
  - docs/get-started/python-quickstart/
  - docs/develop

allowed_target_extensions: [.md]
enable_code_dedenting: false
